services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    volumes:
      - ./:/app/
    depends_on:
      - chroma
    networks:
      - net
    # keep container running, only for development
    command: tail -f /dev/null

  chroma:
    # https://github.com/chroma-core/chroma/pkgs/container/chroma
    image: ghcr.io/chroma-core/chroma:1.0.8.dev9
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net
    restart: unless-stopped

volumes:
  index_data:
    driver: local

networks:
  net:
    driver: bridge
